UPEEL2019_2020/UPEEL2019_2020/Controllers/AddShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UpExcise.Models;
using UpExcise.Repository;

namespace UEEL2019_20.Controllers
{
    public class AddShopController : Controller
    {
        IShopDetails objShop;
        public AddShopController()
        {
            objShop = new ShopDetails();
            //objdal = new Repository.RandamizationNew();
        }

        // GET: AddShop
        public ActionResult AddShop()
        {
          //  TempData["dist"] = ViewBag.DisLst = objShop.DllDistrict().Where(a => a.Value == UserSession.LoggedInUserDistictId.ToString());
            TempData["dist"] = ViewBag.DisLst = objShop.DllDistrict().Where(a => a.Value == "163");
            //int flag = objShop.CheckShopDSCStatus(UserSession.LoggedInUserDistictId.ToString());
            int flag = objShop.CheckShopDSCStatus("163");
            if (flag > 0)
                ViewBag.Dsc = "Done";
            // ViewBag.DistCode = UserSession.LoggedInUserDistictId;
            return View();
        }
        [HttpGet]
        //public ActionResult GetShops()
        //{
        //    shopDetails obj = new shopDetails();
        //    obj.distCode = 0;
        //    //IEnumerable<shopDetails> products = objShop.ShopList(obj, UserSession.LoggedInUserDistictId.ToString());
        //    IEnumerable<shopDetails> products = objShop.ShopList(obj, "163");
        //    var Shop = products.OrderBy(a => a.ShopNameH).ToList();
        //    return Json(new { data = Shop }, JsonRequestBehavior.AllowGet);
        //}
        public JsonResult GetShops()
        {
            shopDetails obj = new shopDetails();
            obj.distCode = Convert.ToInt32(TempData.Peek("distcode"));
            obj.ShopType = Convert.ToString(TempData.Peek("shopType"));
            //IEnumerable<shopDetails> products = objShop.ShopList(obj, UserSession.LoggedInUserDistictId.ToString());
            IEnumerable<shopDetails> products = objShop.ShopList(obj, "163");
            ViewBag.GetTehsilName = objShop.GetTehsilNameByDistrict(obj);
            ViewBag.GetThanaName = objShop.GetThanaNameByDistrict(obj);
            var Shop = products.OrderBy(a => a.ShopNameH).ToList();
            return Json(new { data = Shop }, JsonRequestBehavior.AllowGet);
        }
        public string setDistAndShoptype(string distcode, string shopType, string distName, string shopName)
        {
            TempData["distName"] = distName;
            TempData["shopName"] = shopName;
            TempData["distcode"] = distcode;
            TempData["shopType"] = shopType;
            return "true";
        }
        [HttpGet]
        public ActionResult Save(int id)
        {
            shopDetails obj = new shopDetails();
            obj.distCode = Convert.ToInt32(TempData.Peek("distcode"));
            obj.ShopType = Convert.ToString(TempData.Peek("shopType"));
            ViewBag.distName = TempData.Peek("distName").ToString();
            ViewBag.shopName = TempData.Peek("shopName").ToString();
            ViewBag.GetTehsilName = objShop.GetTehsilNameByDistrict(obj);
            ViewBag.GetThanaName = objShop.GetThanaNameByDistrict(obj);
            ViewBag.ShopTYPE = TempData.Peek("shopType").ToString();
            //var Shop = objShop.ShopList(obj, UserSession.LoggedInUserDistictId.ToString()).Where(a => Convert.ToInt32(a.ShopID) == id).FirstOrDefault();
            var Shop = objShop.ShopList(obj, "163").Where(a => Convert.ToInt32(a.ShopID) == id).FirstOrDefault();

            return View(Shop);

        }

        [HttpPost]
        public ActionResult Save(shopDetails emp)
        {
            ViewBag.DisLst = TempData["dist"];
            emp.distCode = Convert.ToInt32(TempData.Peek("distcode"));
            emp.ShopType = TempData.Peek("shopType").ToString();
            ViewBag.ShopTYPE = TempData.Peek("shopType").ToString();
            TempData["TehsilCode"] = emp.TehsilCodeCensus;
            emp.ShopNameE = emp.ShopNameE.ToUpper();
            bool status = false;
            if (ModelState.IsValid)
            {
                if (Convert.ToInt32(emp.ShopID) > 0)
                {
                    objShop.UpdateShop(emp);
                }
                else
                {
                    objShop.SaveShop(emp);
                }
                status = true;
            }
            return new JsonResult { Data = new { status = status } };
        }
        public ActionResult SaveApplicant(int id)
        {
            BOShopWiseApplicant obj = new BOShopWiseApplicant();
            obj.DistrictCode = Convert.ToInt32(TempData.Peek("distcode"));
            obj.Shoptype = Convert.ToString(TempData.Peek("shopType"));
            obj.Shopid = id.ToString();
            ViewBag.distName = TempData.Peek("distName").ToString();
            ViewBag.shopName = TempData.Peek("shopName").ToString(); 
            ViewBag.ShopTYPE = TempData.Peek("shopType").ToString();
            var App = objShop.ShopWiseApplincatDetails(obj).FirstOrDefault();

            return View(App);

        }
    }
}

UPEEL2019_2020/UPEEL2019_2020/Views/AddShop/SaveApplicant.cshtml
@model UpExcise.Models.BOShopWiseApplicant



<div>
        @using (Html.BeginForm("SaveApplicant", "AddShop", FormMethod.Post, new { id = "popupForm" }))
        {
            @Html.ValidationSummary(true)

            if (Model != null && Convert.ToInt32(Model.Shopid) > 0)
            {
                <h2 style="font-size: 20px; text-align: center; color: #33b35a; margin-top: 5%;">Edit Shop Allotee Information</h2>
                @Html.HiddenFor(a => a.Shopid)
                <div class="form-group" style="text-align: center; color: #17a2b8; font-size: 17px; margin-top: 3%;">
                    <label style="font-size: medium; color: #393836;">जिला का नाम - </label>
                    @Html.DisplayFor(a => Model.DistrictName)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <label style="font-size: medium; color: #393836;">दुकान का प्रकार - </label>
                  
                    @Html.DisplayFor(a => Model.Shoptype)  <br />
                    <label style="font-size: medium; color: #393836;">दुकान का नाम- </label>

                    @Html.DisplayFor(a => Model.ShopName)
                </div>


                <div class="row">

                    <div class="col-md-12">
                        <div class="box">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>आवंटि का नाम - </label>
                                        @Html.TextBoxFor(m => Model.ApplicantName, new { @id = "txt_ApplicantName", @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.ApplicantName)
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>आवंटि का आधार - </label>
                                        @Html.TextBoxFor(m => Model.ApplicantAadhar, new { @id = "txt_ApplicantAadhar", @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.ApplicantAadhar)

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="box">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>आवंटि का पैन कार्ड संख्या - </label>
                                        @Html.TextBoxFor(m => Model.ApplicantPAN, new { @id = "txt_ApplicantPAN", @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.ApplicantName)
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>आवंटि का मोबाइल नंबर  - </label>
                                        @Html.TextBoxFor(m => Model.ApplicantPAN, new { @id = "txt_ApplicantMobile", @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.ApplicantPAN)

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>


                <div class="row">

                    <div class="col-md-12">
                        <div class="box">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>सह-आवंटि का नाम - </label>
                                        @Html.TextBoxFor(m => Model.CoApplicantName, new { @id = "txt_CoApplicantName", @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.ApplicantName)
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>सह-आवंटि का आधार - </label>
                                        @Html.TextBoxFor(m => Model.CoApplicantAadhar, new { @id = "txt_CoApplicantAadhar", @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.ApplicantAadhar)

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="box">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>सह-आवंटि का पैन कार्ड संख्या - </label>
                                        @Html.TextBoxFor(m => Model.CoApplicantPAN, new { @id = "txt_CoApplicantPAN", @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.ApplicantName)
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>सह-आवंटि का मोबाइल नंबर  - </label>
                                        @Html.TextBoxFor(m => Model.CoApplicantPAN, new { @id = "txt_CoApplicantMobile", @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.ApplicantPAN)

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>



                <div>
                    <center><input type="button" value="सुरक्षित करे" onclick="showValidation(this)" class="save_btn btn btn-primary" /></center>
                </div>





            }
        }


    </div>

@*<script type="text/javascript">

        function showValidation(obj) {

            if ($('#ddlGetTehsilName').val() == "0") {
                swal("Please Select Tehsil.");
                event.preventDefault();
                return false;
            }
            if ($('#ddlGetThanaName').val() == "0") {
                swal("Please Select Thana.");
                event.preventDefault();
                return false;
            }

            if ($('#ddlCircleType').val() == "" && $('#ddlSectorType').val() == "") {
                swal("Please Select atleast one Circle/Sector.");
                event.preventDefault();
                return false;
            }

            //if ($('#ddlSectorType').val() == "") {
            //    swal("Please Select Sector.");
            //    event.preventDefault();
            //    return false;
            //}

            if ($('#ddlAreaType').val() == "") {
                swal("Please Select Area.");
                event.preventDefault();
                return false;
            }


            if ($('#txt_LicenseFee').val() == "" && $('#txt_MGQ').val() == undefined) {
                swal("Please Enter the License Fee Amount.");
                event.preventDefault();
                return false;
            }

            if ($('#txt_MGQ').val() == "" && $('#txt_LicenseFee').val() == undefined) {
                swal("Please Enter the MGQ Amount.");
                event.preventDefault();
                return false;
            }

            if ($('#ShopNameHin').val() == "") {
                swal("Please fill the Hindi Name of Shop.");
                event.preventDefault();
                return false;
            }


            if ($('#ShopNameEng').val() == "") {
                swal("Please fill the English Name of Shop.");
                event.preventDefault();
                return false;
            }


            if (!(window.confirm("सुरक्षित करने से पूर्व दुकान से सम्बंधित समस्त सूचनाओ की शुद्धता की जांच कर ली गयी है |"))) {
                event.preventDefault();
                return false;
            }

            //if()
            //var regex = new RegExp("^[a-zA-Z0-9 ]+$");
            //var str = String.fromCharCode(!e.charCode ? e.which : e.charCode);
            //if (regex.test(str)) {
            //    return true;
            //}

            //e.preventDefault();
            //return false;


        }






    </script>*@